# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0007_auto_20170524_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
