# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='imagen',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
