# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0010_auto_20170525_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='imagen',
            field=models.ImageField(blank=True, default='', upload_to='pics'),
        ),
    ]
