# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0011_auto_20170525_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciertos', models.IntegerField()),
                ('fallos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='historico',
            name='jugador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='preguntas.Jugador'),
        ),
    ]
