# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0012_auto_20170526_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='c1',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='c2',
            field=models.CharField(default='2', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='c3',
            field=models.CharField(default='3', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.IntegerField(default='1'),
        ),
    ]
